### PR TITLE
Update driver list and do some polishing

### PR DESCRIPTION
**Pull request by MBjoern**

### CODE REVIEW

**Review by winkj — APPROVED** [review]
Looks good to me, thanks for the updates

**Comment by MBjoern** [comment]
Sorry for the inconvenience, but I had another go on the file and tried to create some more short cuts to facilitate navigation.. After all it got quite big by now :D

By the way, the tables are all generated with the details fetched via GitHub API requests.

**Comment by winkj** [comment]
Still looking good (and github kept the approval after the push anyway?)

Regarding the size: we could potentially split things up into multiple repositories, which could make it easier to split API generated tables from prose, too.

**Comment by rnestler** [comment]
> and github kept the approval after the push anyway?

This can be changed in the settings.

**Pull request merged**
